### ISSUE TITLE
Suggestion: rename `AppUpdate` to `Update`

### ISSUE THREAD

**Issue by lomirus** [Relm4/Relm4#154]
I saw in the example of the readme that there are several statements like below (omitting some irrelevant codes):
```rs
impl Model for AppModel {}
impl Widgets for AppWidgets {}
```
and such statement in the documentation:
```rs
impl Components for AppComponents {}
```
We can easily see from them that they all obey such a format: `impl X for AppX {}`.

However, there is an exception: 
```rs
impl AppUpdate for AppModel {}
```

Though there's nothing like `impl Msg for AppMsg` and it may be hard to implement if we need, but still, to keep the consistency, I suggest to remove the `App-` prefix for trait `AppUpdate`, to make it `impl Update for AppModel {}` at least.

**Comment by AaronErhardt** [comment]
You're right, the naming isn't perfect, but `AppUpdate` is called like this to avoid confusion with `ComponentUpdate`.

I hope you don't mind if I close this issue. I won't introduce a breaking change in the current stable version and in the upcoming version this will be fixed anyway because there's only one `Component` trait for everything.

**Comment by lomirus** [comment]
@AaronErhardt  Thanks for your reply. Actually I didn't notice the `ComponentUpdate` when I posted this issue. But now I am looking forward to your only-`Component` version.
