### ISSUE TITLE
Unstable doc features should not use `cfg(doc)`

### ISSUE THREAD

**Issue by euclio** [Relm4/Relm4#171]
Gating unstable doc features like `doc_cfg` behind `cfg(doc())` is not a good solution, because `cfg(doc)` is always set by `rustdoc`, even on stable. This causes errors when running `cargo doc` on stable.

We should gate on an explicit cfg like `docsrs` and then only supply that `cfg` when building docs for the website, so that users can build the documentation locally without unstable features. [Here's what tokio does.](https://github.com/tokio-rs/tokio/blob/master/tokio/Cargo.toml#L148-L151)

**Comment by AaronErhardt** [comment]
Sounds good, but I don't think we can use `[package.metadata.docs.rs]` because we can't use docs.rs because of GTK4 and the other dependencies. Tokio seems to use docs.rs but the configuration is a good start. Maybe we can add a feature to Cargo.toml from the doc script, just like the unstable `cfg(doc)` feature is added to lib.rs.

I wonder why this hasn't been stabilized since docs.rs seems to have used this for ages.

**Comment by euclio** [comment]
Yep, I realize that we don't use docs.rs due to the dependencies, I'm just pointing to it as an example of passing the manual `--cfg` flag.
