### ISSUE TITLE
`LeafletPage` has no `default` method

### ISSUE THREAD

**Issue by lomirus** [Relm4/Relm4#175]
I am trying to use the libadwaita to create a leaflet widget.
```rust
#[relm4::widget(pub)]
impl Widgets<MainPageModel, AppModel> for MainPageWidgets {
    view! {
        &adw::Leaflet {
            append: sidebar = &gtk::Box {
            },
            append = &adw::LeafletPage {
                set_child: &gtk::Separator::new(Orientation::Horizontal)
            },
            append: chatroom = &gtk::Box {
            },
        }
    }
}
```

And it gave me such error:

```
no function or associated item named `default` found for struct `LeafletPage` in the current scope
function or associated item not found in `LeafletPage`
```

However, this ui template works (partly copied from [this](https://github.com/raduzaharia-medium/gtk-rss-reader-mock-ui/blob/main/content/main-window.ui)):
```xml

<child>
    <object class="AdwLeaflet" id="leaflet">
        <!-- <property name="can-navigate-back">True</property> -->
        <property name="can-swipe-back">True</property>
        <child>
            <object class="GtkBox"></object>
        </child>
        <child>
            <object class="AdwLeafletPage">
                <property name="navigatable">False</property>
                <property name="child">
                    <object class="GtkSeparator" />
                </property>
            </object>
        </child>
        <child>
            <object class="GtkBox"></object>
        </child>
    </object>
</child>
```

**Comment by AaronErhardt** [comment]
This is caused by the API of libadwaita. We opened an issue for that because it's not a great API for Relm4, but they decided to keep it like it was.

In short, you can't construct a `LeafletPage` directly using Rust code, but you have to call a method on `Leaflet` to get a page. If you want to access the page returned by these methods, you can use the "returned widget" syntax that was added just for this purpose:

```rust
            append = &gtk::Separator::new(Orientation::Horizontal) {
            } -> {
                // Access the page here
                set_name: Some("page_name"),
            },
```

Example: https://github.com/Relm4/Relm4/blob/main/relm4-examples/libadwaita/examples/view-switcher.rs#L88

**Comment by lomirus** [comment]
@AaronErhardt  Thanks for your solution. Perhaps we should also add an example about the leaflet. I am working on a project including this widget, so I can try to make a PR once I finish it though it still needs some time now.
