### ISSUE TITLE
Why different syntax for setting properties and widgets in view! macro?

### ISSUE THREAD

**Issue by pkolaczk** [Relm4/Relm4#238]
I'm new to Relm4, and one of the first things that confused me was the syntax distinction between ':' and '='.

```
set_label: "label"
```

and

```
append = gtk::Box { ... }
```

AFAIK, both end up calling a function with the name specified on the left side with a value of the expression on the right side. I don't get the semantic difference. Why can't we use ':' for all properties, including widgets?

I also noticed that when using = in the view! macro called inside a function, it creates a variable in the outer scope. But now that seems to work differently than in a top-level view! that is a part of the impl, so it adds to my confusion.

**Comment by AaronErhardt** [comment]
The reason is very simple: The widgets need to be nested and also put into the widgets struct. Properties are regular Rust expressions, whereas widgets need more code generation by the macro (initialization, assignments, struct fields etc.).

Actually, all variants of `view!` create variables in outer scope, but through `view_output!()` the widgets are assigned to the widgets struct which takes ownership of the variables.
