### ISSUE TITLE
Conditional returns in pre/post_view should be denied

### ISSUE THREAD

**Issue by euclio** [Relm4/Relm4#256]
My application has code like this in pre_view:

```
        let file = match &self.file {
            Some(file) => file,
            None => return,
        };
```

Since the removal of the IIFEs that wrap pre and post_view, this code silently skips the view update. The macro should emit an error for code like this.

**Comment by AaronErhardt** [comment]
The [pre-view-return test](https://github.com/Relm4/Relm4/blob/main/relm4-macros/tests/ui/compile-fail/pre-view-return.rs) already makes sure that returning from pre_view will throw a warning. Of course we could add a `#[deny(unreachable_code)]` in the macro codegen to make this a hard error. And post_view is actually allowed to return early since nothing unexpected can happen anyway.

**Comment by euclio** [comment]
The macro doesn't emit an `unreachable_code` warning in this case because the code is reachable in some cases.
