### ISSUE TITLE
Enabling features of GTK dependencies

### ISSUE THREAD

**Issue by euclio** [Relm4/Relm4#322]
I'd like to enable the `v2_70` feature in glib, but there's currently no obvious way to do this through Relm4.

I realize this is intended behavior in that features of transitive dependencies are supposed to be implementation details, but maybe there's a way to expose this, or at least a workaround?

**Comment by AaronErhardt** [comment]
Adding features like "glib_v2_70" and "gtk_v4_8" would work but also is quite tedious. So I had the idea to add features like "gnome_43" (or "gnome_sdk_43") that include the library versions of a specific GNOME SDK. This makes sense anyway since most distros and the flatpak runtimes should have the same baseline of versions if they ship for a certain GNOME release.

If you agree with this, we can also ask the gtk4-rs maintainers whether they would like to add this themselves, which would make things simpler for us (because Relm4 uses re-exports from the gtk4 crate, then we only have to take care of libadwaita and maybe  libpanel) and would be nice-to-have feature for gtk4-rs too.

**Comment by euclio** [comment]
I like the idea. I agree that exposing each individual feature would be too verbose.

**Comment by AaronErhardt** [comment]
The `gnome_42` and `gnome_43` feature flags have been merged into gtk4-rs: https://github.com/gtk-rs/gtk4-rs/pull/1160

Now we only need to wait for the next gtk4-rs release to add this to Relm4 too.
