### ISSUE TITLE
Add macOS and Windows to CI?

### ISSUE THREAD

**Issue by nirvdrum** [Relm4/Relm4#48]
I really like the look of the relm4 API, but I can't figure out how to run the examples on either macOS or Windows. Everything worked great out of the box in Ubuntu. I've never written a GTK app before and I've read through the linked GTK4 docs, but I still can't work out how to get the correct files where they need to be for relm4 or gtk-rs or whatever else to find what it needs. I think a lot of this documentation assumes you've previously written GTK apps and just need to update for GTK4.

In any event, I'm not having much success getting started. It would be immensely helpful if the GitHub Actions configuration built the examples on macOS and Windows since that would show a scripted approach to running everything successfully.

**Comment by AaronErhardt** [comment]
@nirvdrum thanks for your feedback. I'm aware of that issue and together with the devs at gtk-rs we're working towards better installation instructions (e. g. see this PR https://github.com/gtk-rs/gtk4-rs/pull/606). Having a CI pipeline for Windows and MacOS would definitely be great but first I'd try to get the instructions in the gtk-rs book ready. 

Btw. instructions for MacOS and Linux are available here: https://www.gtk.org/docs/installations/
Only the Windows instructions seem to be outdated. And btw. if you could confirm that the MacOS instructions work for gtk4-rs that'd be great :wink: 

@Hofer-Julian how is the progress so far? Do you need any help?

**Comment by nirvdrum** [comment]
Great to hear there's activity on improving it. Unfortunately, the docs at https://www.gtk.org/docs/installations/macos/ are where I've been struggling. I'd love to just have a Homebrew command to install the necessary libraries, but that doesn't seem to be an option. The "Building" and "All-in-one bundles" sections talk about building and packaging the library with the application, but that looks like it's for a non-Rust ecosystem. I've run the script from the "Getting Started" section, but that alone was insufficient to build the examples, and there's no docs I've been able to find on next steps.

Maybe I'm trying to run before I walk by building a Rust app with GTK before having done so with C, but I haven't found the installations link terribly helpful. I'm sure if I invested a weekend into this I could probably figure out what env vars to set and get everything linking together. Part of what I enjoy about the Rust ecosystem is I haven't really needed to do that thus far. I appreciate that we're linking in a C library, but I was really hoping a doc on linking to the GTK libraries or maybe a `cfg` value to point at the libraries.

Maybe I should open an enhancement issue against gtk-rs instead. Their docs also just point at the GTK installation docs, but similarly don't say what steps are necessary after installing. I can see the value in not wanting to have to also document this other massive library, which is why I thought the CI configuration would provide a known set of steps to getting a working build environment.

**Comment by Hofer-Julian** [comment]
> @Hofer-Julian how is the progress so far? Do you need any help?

I rephrased your PR a bit and will open a PR as soon as I have a few hours available.
Will tag you then if you are willing to review.

**Comment by AaronErhardt** [comment]
@nirvdrum actually, there is a homebrew package. Maybe `brew install gtk4` does the job?
The GTK docs suggest that this doesn't result in the best integration but maybe that works well enough. Also, in general linking Rust is not harder than linking C.

Feel free to open an issue. But I think - at least for the MacOS problem - you should open it here: https://gitlab.gnome.org/GNOME/gtk-osx/

**Comment by ruifengx** [comment]
I have also been struggling for building GTK4 on Windows for a while. It is especially a pain for the MSVC toolchain, because I believe for the GCC toolchain one can always fall back to the prebuilt versions in MSYS2. I tried `gvsbuild` and also building all the libraries manually. GTK4 itself compiles fine, but the same cannot be said for `gobject-introspection`, `librsvg` (for `pixbufloader-svg.dll`) and `libadwaita`. My final solution was to (ab)use GitHub Actions to produce a binary artifact for me to use locally (it worked pretty well), and the CI script is available [here](https://github.com/ruifengx/gnome-build/blob/master/.github/workflows/build.yaml). The prebuilt binaries are also [ready to be downloaded](https://github.com/ruifengx/gnome-build/releases/tag/v0.1-20220403), and one can always fork that repo to make his own prebuilt release, too.

**Comment by AaronErhardt** [comment]
@ruifengx have you tried the instruction from [here](https://gtk-rs.org/gtk4-rs/stable/latest/book/installation_windows.html)?
Also, It'd be great if you could document your knowledge (Windows stuff can be hard to figure out, the section in the gtk-rs book took days to get it working properly). Maybe you can even add an optional workflow to [gtk-rust-template](https://gitlab.gnome.org/World/Rust/gtk-rust-template/-/tree/master) or here at Relm4 for reference.

**Comment by ruifengx** [comment]
@AaronErhardt Yes, I was following the instructions from that book, and indeed it was really helpful, yet only for compiling GTK4 itself. (The detailed procedure for building the libraries is available in [the CI script](https://github.com/ruifengx/gnome-build/blob/master/.github/workflows/build.yaml), and an overview is available as [the release notes here](https://github.com/ruifengx/gnome-build/releases/tag/v0.1-20220403).) I will also try to summarise the essential points of my findings below.

The first thing I found out is that only GTK4 itself is not enough, because SVG icons from the Adwaita icon theme will not load. After some investigation, it turns out that I also need `pixbufloader-svg.dll` in `$INSTALL_DIR/lib/gdk-pixbuf-2.0/2.10.0/loaders` for this purpose, and that DLL is part of `librsvg`.

And of course my next goal is to build `librsvg`, and this is where the real pain starts to appear. The main `librsvg` library is written in Rust, which comes as a lifesaver, but the part controlling the generation of the pixbuf loader I wanted is written in `autotools`, which IMHO is impossible to use on Windows with the MSVC toolchain. Below is a quote of the relevant part in the aforementioned release note:
> Library librsvg offers official support for building on Windows, but it did not work out of the box in our CI build here. Besides, the setup there looks needlessly dynamic to some extent: a static librsvg.lib is first generated by the Rust tool chain, and then converted by MSVC to a DLL. Also, some dependencies are marked optional on Windows in the project, but it seems without those "optional" dependencies the build will always end up in a hard _link error_. Fortunately the main librsvg library is now developed in Rust, and we only care about the SVG loader for gdk-pixbuf anyway, so we choose a different approach here: first, we prepare all the dependencies (including the _optional_ ones for the reason stated above) and use Cargo to produce a static library `librsvg.lib`; after that we link the `pixbufloader-svg.dll` with `cl` manually (for the detailed command, see [our build script](https://github.com/ruifengx/gnome-build/blob/93cfd1d8fb4cbd2ca50c1fa9b3d569a51cd3b63a/.github/workflows/build.yaml#L89)). The loaders cache is then updated by [invoking `gdk-pixbuf-query-loaders --update-cache`](https://github.com/ruifengx/gnome-build/blob/93cfd1d8fb4cbd2ca50c1fa9b3d569a51cd3b63a/.github/workflows/build.yaml#L92).

Other dependencies can be compiled using the normal _official_ procedure (CMake/Meson), but with one catch: I cannot make `gobject-introspection` build properly with the latest Meson, and I believe it is a bug in the `meson.build` script in GI.

And finally some sidenote: on my local machine, `gvsbuild` and manual build both failed, but in different stages, I presume. Now in retrospection, I believe the failure in manual build was definitely due to wrong Meson version for GI; but still I don't quite understand `gvsbuild`, so I don't have very much to say about that. I had some suspicions, though: my non-English non-Unicode system locale, my non-English MSVC toolchain, and/or my other tools in PATH (the last one is not very likely, because I tried clearing PATH before the whole build). In general, I won't recommend anyone try building the whole dependency tree on his local PC, because there are just so many things that might go wrong. Since the MSVC toolchains (for VS2017, VS2019, and VS2022) are binary compatible to one another, I would recommend maintaining a prebuilt binary release for everyone (ideally by GNOME, in their CI/CD process perhaps, even a use-at-your-own-risk version; but of course only if targetting MSVC on Windows is at all supported officially), and the whole problem is solved.
