### ISSUE TITLE
Error when calling `RelmApp::run` from a pre-existing Adwaita app

### ISSUE THREAD

**Issue by hwittenborn** [Relm4/Relm4#557]
I'm in the middle of incrementally migrating an application from stock Adwaita to using Relm4. As part of the procedure, I'm first migrating a tiny part of my codebase (one of the windows in my application) to use Relm4.

My application already has it's `adw::Application` set up by the time everything gets to the `RelmApp` call. I'm not sure if it's related but this code is causing `g_application_parse_command_line: assertion '!application->priv->options_parsed' failed` to be shown, and the Relm4 window to not pop up:

```rust
let app = RelmApp::from_app(adw_app.clone());
app.run::<LoginModel>(());
```

The parts of GTK/Adwaita being called to set up my application are the following:

```rust
gtk4::init().unwrap();
...
let app = adw::Application::builder().application_id("my.Application.Id").build();
...
app.run_with_args::<&str>(&[]);
```

It looks like Relm4 may be attempting to re-call `app.run_with_args` (or similar) from GTK/Libadwaita, though I'm not positive. Is there any way I might be able to get around this?

**Comment by AaronErhardt** [comment]
I think you can't run an application twice and that's what happens when you run the RelmApp. In this case, RelmApp might be too restricted for you and you can just do the setup manually, like in this example: https://github.com/Relm4/Relm4/blob/main/examples/settings_list.rs#L19

Actually, you can even spawn Relm4 components from anywhere in a regular gtk-rs app and they will still work as expected :)

**Comment by hwittenborn** [comment]
I just found out about the way to use child components - I'm still fairly new to Relm4 but it all makes enough sense, and I was able to get everything working now.

I'll go ahead and get this closed up, thanks for the help! :)
