### ISSUE TITLE
Resizeable and expandable columns with TypedColumnView

### ISSUE THREAD

**Issue by Lynnesbian** [Relm4/Relm4#588]
GTK has the ability to make columns resizeable, as seen [here](https://docs.rs/gtk4/0.7.3/gtk4/struct.ColumnViewColumn.html#method.set_resizable) in the Rust bindings for GTK4, and [here](https://docs.gtk.org/gtk4/method.ColumnViewColumn.set_resizable.html) in the GTK4 documentation. However, Relm4's `TypedColumnView` does not seem to expose that functionality. This feature would be very useful for the program I'm currently creating.

Similarly, there is also a setting that causes the columns to expand to take up all available space ([Rust docs](https://docs.rs/gtk4/0.7.3/gtk4/struct.ColumnViewColumn.html#method.set_expand), [GTK docs](https://docs.gtk.org/gtk4/method.ColumnViewColumn.set_expand.html)). This would also be quite useful for my app.

Could these features be exposed in the Relm4 bindings?

**Comment by AaronErhardt** [comment]
Sure, this sounds like it should be easy to add. Either we add specific methods to [`RelmColumn`](https://docs.rs/relm4/latest/relm4/typed_list_view/trait.RelmColumn.html) that returns bools for resizable and expand or we add a single method that allows you to modify the `gtk::ColumnViewColumn` before it is inserted.

Do you want to take a look at the code? Otherwise I can work on this myself, but it might take some time before I can work on that.

**Comment by Lynnesbian** [comment]
Sure, I'll take a look and see what I can do. I might add consts for it in the same way that `LabelColumn` has the [`ENABLE_SORT`](https://docs.rs/relm4/latest/relm4/typed_list_view/trait.LabelColumn.html#associatedconstant.ENABLE_SORT) const.
