### ISSUE TITLE
Please enable libadwaita v1_6 feature

### ISSUE THREAD

**Issue by blissd** [Relm4/Relm4#673]
Hi. Please would you enable the v1_6 feature flag for libadwaita so I can use the new  [MultiLayoutView](https://docs.rs/libadwaita/0.7.0/libadwaita/struct.MultiLayoutView.html)?

**Comment by AaronErhardt** [comment]
You can already do this by adding libadwaita to your dependencies with the v1_6 feature enabled. Eventually, you will be able to enable this feature in Relm4 with the gnome_47 feature flag, but since neither libadwaita 1.6 nor GNOME 47 are released yet, it doesn't make sense to add this to Relm4 yet.

**Comment by blissd** [comment]
Thanks letting me know. I had tried adding the libadwaita crate with the feature enabled, but that produced other errors for me. I'll wait for GNOME 47 to be release and Relm4 to be updated, I think.
